# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-12 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.PositiveIntegerField(blank=True, null=True)),
                ('ifsc_code', models.CharField(max_length=25)),
                ('branch_name', models.CharField(max_length=25)),
                ('account_type', models.CharField(choices=[('saving', 'Saving Account'), ('current', 'Current Account'), ('salary', 'Salary Account')], default='salary', max_length=25)),
            ],
        ),
    ]
